name: coding_test
description: Inova coding test

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.3
  json_serializable: ^6.1.5
  dartz: ^0.10.1
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.0
  build_runner:
flutter:

  uses-material-design: true

  assets:
    - assets/
